spomky_labs_cors:
    allow_origins:
        - '*'
    allow_methods:
        - GET
        - POST
        - DELETE
    allow_headers:
        - Content-Type
        - Access-Control-Allow-Headers
        - Authorization
        - X-Requested-With
